# Generated by Django 5.2.3 on 2025-12-04 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_address_user_date_of_birth_user_is_nin_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('transaction_type', models.CharField(blank=True, max_length=20, null=True)),
                ('total_transactions', models.IntegerField(default=0)),
                ('total_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_expense', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_change', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('statement_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
