# Generated by Django 5.2.3 on 2025-12-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_beneficiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='counterparty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
